baseURL = "https://cbluem.de"
languageCode = "en-us"
title = "Christoph Blüm"
theme = "personal-web"
copyright="© Christoph Blüm"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Christoph :wave:"
  sub = "I'm an Electrical Engineering Student and Systemsadministrator"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "technologies"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#112f41"
  mainSections = ['portfolio', 'post'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  banner = "/images/oh-no-anyway.gif"
  h1 = 'Oh no!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/sidebar.png'
  gradientOverlay = 'rgba(0,0,0,0),rgba(0,0,0,0)' # 'rgba(150,60,70,0),rgba(60,150,70,0)'
  logo = '/images/portrait.jpg'

[params.assets]
  favicon = "/images/favicon-96x96.ico"
  customCSS = ""

[params.social]
  github = "https://github.com/Chr1s70ph"
  # twitter = "https://twitter.com/"
  linkedin = "www.linkedin.com/in/christoph-bluem"
  # medium = "https://medium.com/"
  # codepen = "https://codepen.io/"
  # facebook = "https://www.facebook.com/"
  # youtube = "https://www.youtube.com/"
  instagram = "https://www.instagram.com/bl.christoph"
  gitlab = "https://gitlab.com/ChristophBluem"
  # keybase = "https://keybase.io/"

[params.contact]
  email = "webmaster@cbluem.de"
  text= "Email" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Projects"
  title = "My Projects"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog section"
  url = "/post/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
